### ISSUE TITLE
Geometry_oM: Possibile IImutable interface on the PlanarSurface

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#431] opened 2019-03-08 16:03 UTC
Could add `IImutable` interface to planar surface to make it safer in terms of possibility of creating invalid ones.

The `InnerBoundaries` will need to be a `ReadOnlyCollection` rather than a list, which might make it a bit more awkward to work with, but should not pose to big of a problem.

**Comment by kThorsager** [comment] 2020-04-22 10:17
duplicate of #676 
removing this one as the other one has more discussion and links

**Closed by kThorsager** 2020-04-22 10:17 UTC
Labels: severity:low, type:feature
