### ISSUE TITLE
BHoM_v4.3.beta.0 crashing with Dynamo in Revit 2022.1

### ISSUE THREAD

**Issue by koliveirast** [BHoM/BHoM#1303] opened 2021-10-13 11:07 UTC
#### Description:
When I try to run the BHoM_v4.3.beta.0 in Dynamo (Core 2.12.0.5650 / Revit 2.12.0.5740), occurs an error and the Dynamo application doesn't open.

#### Steps to reproduce:
Open Revit 2022.1 and try to open Dynamo in the Manage tab.

#### Expected behaviour:
![image](https://user-images.githubusercontent.com/92438119/137121582-a07a999f-b876-4956-98da-37e659c604e0.png)

#### Test file(s):
It occurs with all files wheter they are new or in use.

**Comment by FraserGreenroyd** [comment] 2022-01-10 10:10
@pawelbaran I think we looked into this in November didn't we? What was the verdict?

**Comment by pawelbaran** [comment] 2022-01-10 10:18
Yeah you are right @FraserGreenroyd - apologies I have not seen this thread. The problem was caused by BHoM and Dynamo using different versions of the same assemblies, which Dynamo could not handle. It has been resolved through https://github.com/BHoM/Revit_Toolkit/pull/1137 - should be fine now, so I will close this issue, but please reopen it (and ideally ping me) in case it reoccurs. Thanks!

**Closed by pawelbaran** 2022-01-10 10:18 UTC
Labels: type:bug
